---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rebooto.work
  resources:
  - reboots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rebooto.work
  resources:
  - reboots/finalizers
  verbs:
  - update
- apiGroups:
  - rebooto.work
  resources:
  - reboots/status
  verbs:
  - get
  - patch
  - update
